# Generated by Django 4.2.11 on 2024-05-16 15:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_smthng_wizard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capital',
            old_name='location',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='location',
            new_name='geom',
        ),
        migrations.RemoveField(
            model_name='country',
            name='location',
        ),
        migrations.AddField(
            model_name='country',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, default=None, null=True, srid=4326),
        ),
    ]
